[project]
name = "datascienceprogramming-ds250"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brycen Taylor", email = "bkt443@byui.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "lets-plot>=4.11.0",
    "palmerpenguins>=0.1.6",
]

[project.scripts]
datascienceprogramming-ds250 = "datascienceprogramming_ds250:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
